remote_theme: pages-themes/hacker@v0.2.0
title: Sina Cyrus Portfolio
description: Showcasing Some of My Recent Projects
og: ![Sina Cyrus](https://github.com/cyruss258/cyruss258.github.io/blob/main/IMG-20220828-WA0004.jpg)
