remote_theme: pages-themes/hacker@v0.2.0
title: Sina Cyrus Portfolio
description: Showcasing Some of My Recent Projects
og: ![Sina Cyrus](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")
